### ISSUE TITLE
Make the clock use more screen real estate in ambient mode

### ISSUE THREAD

**Issue by Jnss98b** [rdnt/m8#9]
**Describe the issue**
Currently, the ambient mode only shows the time but the digits are roughly the same size as when the watch is active. I think that the face should use a bigger clock in ambient mode. On a watch with a thicker bezel like the pixel watch this makes the face looks a bit odd in ambient mode. Maybe it can be an added option?

**Device info:**
 - WearOS version: 3.5 (Android 11)
 - Device model: Pixel Watch

**Comment by rdnt** [comment]
I agree. I initially did not make it this way for battery consumption's sake, but it can indeed be added as an option. Will consider it for the next release. Thank you for the feedback! :)

**Comment by Jnss98b** [comment]
Thank you for considering it as an option! I get the battery consumption concern but it honestly would use as many pixels if not fewer than a typical watch face with 2 complications in ambient mode especially with the clock in outline mode and also I wouldn't mind trading a bit of battery life for more glanceability anyway

**Comment by rdnt** [comment]
Released on open testing: v2.9.6-beta1

**Comment by Jnss98b** [comment]
Nice! Will check it out now

**Comment by Jnss98b** [comment]
I found a bug with this feature. The clock size doesn't return to normal when the watch wakes up

![screenshot-2023-04-30-18-37-04](https://user-images.githubusercontent.com/24306400/235379136-124aff3e-63ed-4b73-99d6-52d7e735e42b.png)

**Comment by rdnt** [comment]
@Jnss98b It is possible that this is the old version, will ping you once this one is approved. It's taking a little longer than usual.

**Comment by Jnss98b** [comment]
Oh yes that's a fair point. Also this is weird but somehow the watch says I'm on version 2.8.0

**Comment by rdnt** [comment]
@Jnss98b That is indeed the old BETA version. The new one (v2.9.6) should be released in the next hours I presume.
I had some issues with renaming the repo related to the privacy policy URL changing and they might have delayed the rollout of the release.

**Comment by Jnss98b** [comment]
No worries, good to know that the bug is already addressed though!

**Comment by Jnss98b** [comment]
For now it looks like if I use 1 of the 2 second indicator options this bug won't happen and the time will correctly shrink with an animation when the watch wakes up

**Comment by rdnt** [comment]
@Jnss98b This was indeed one of the bugs I tackled on 2.9.6, if you had the seconds indicator disabled the framerate would not ramp up for the transitions themselves. If viable, please use this workaround for the next 1-2 days till you are enrolled to the new version.

**Comment by rdnt** [comment]
Regarding the big time feature, is the font size on ambient mode your desired result?
I also tried with an even bigger font size but it looked weird for me.

![image](https://user-images.githubusercontent.com/17600197/235379729-caa05744-da2e-4ee0-95d6-84583703c00b.png)

**Comment by Jnss98b** [comment]
I think it looks good enough although I personally would have gone for a slightly bigger font size (as for how much bigger, look at the screenshot of the bug I sent above and imagine the time was big enough to cover half way through the top and bottom complication). Definitely still much better now than before though

**Comment by rdnt** [comment]
@Jnss98b v2.9.6-beta should be deployed now on the open testing track, sorry for that delay.

I will examine again whether I can go with larger fonts, here is how it might look like:

![image](https://user-images.githubusercontent.com/17600197/235463357-27dae1bb-0b49-45c2-a8e8-f356f1f72a04.png)
![image](https://user-images.githubusercontent.com/17600197/235463278-e04bf87c-d22b-4338-9412-d2caf5043056.png)

**Comment by Jnss98b** [comment]
Yep got the update and it works great!

**Comment by Jnss98b** [comment]
> I will examine again whether I can go with larger fonts, here is how it might look like:
 Ah I can kinda see what you mean now. It's bc the font is really angular and when it extends really close to the border of a round watch it looks a bit off

**Comment by rdnt** [comment]
Closing this as I deem it unnecessary to further increase the font size for big ambient mode. I hope this remains in line with your experience as well.

**Comment by Jnss98b** [comment]
It's good as is to me no worries
